use_frameworks!

platform :ios, '10.0'

target 'MarvelService_Example' do
  pod 'MarvelService', :path => '../'

  target 'MarvelService_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
